version: "3"

services:
  ledsvc:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2112:2112

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

