---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cfg
  namespace: iot
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: ledsvc
        scrape_interval: 10s
        static_configs:
          - targets:
              - ledsvc:2112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: iot
spec:
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-container
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prometheus-cfg
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: iot
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
