{
 "title": "LEDs RGB",
 "description": "Iluminação do Quarto",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Visão Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Intensidade do LED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "ledsvc_dim", "legendFormat": "Valor real" }
   ]
  },
  {
   "title": "Distribuição de Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(ledsvc_status + 1) == 1", "legendFormat": "Desligado" },
    { "expr": "(ledsvc_status + 1) == 2", "legendFormat": "Ligado" }
   ]
  },
  {
   "title": "Distribuição dos Modos",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(ledsvc_program + 2) == 1", "legendFormat": "Desligado" },
    { "expr": "(ledsvc_program + 2) == 2", "legendFormat": "Natal" },
    { "expr": "(ledsvc_program + 2) == 3", "legendFormat": "Rastro" },
    { "expr": "(ledsvc_program + 2) == 4", "legendFormat": "Lâmpada" }
   ]
  },
  { "title": "Requisições ao dispositivo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Taxas de Resposta",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(ledsvc_successful_requests) / sum(ledsvc_requests_performed))",
     "legendFormat": "Sucesso"
    },
    {
     "expr": "100 * (sum(ledsvc_error_requests) / sum(ledsvc_requests_performed))",
     "legendFormat": "Erro"
    }
   ]
  },
  {
   "title": "Requisições Totais",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ledsvc_requests_performed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tempo médio de requisições (s)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ledsvc_requests_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}