all: android

android:
	fyne-cross android \
		-app-id com.luksamuk.ledcontrol \
		-icon Icon.png

windows:
	fyne-cross windows \
		-arch=386 \
		-app-id com.luksamuk.ledcontrol \
		-icon Icon.png

linux:
	fyne-cross linux \
		-arch=amd64 \
		-app-id com.luksamuk.ledcontrol \
		-icon Icon.png

